# -*- coding: utf-8 -*-
"""Copy of tparlett_THA2

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1NfYi18CXVyVLNnm7UnrZIGHSWmMY1v83
"""



"""#THA2
This is just a selection of data sources saved to a colab notebook. Further work on these sources is still to come.
"""