# -*- coding: utf-8 -*-
"""tparlett_THA1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1fx6suexZmSnG3tvKKrZ-UTPceYKyaWpQ

##Introduction of the data sources, codebooks, and data formats

The datasets are two County Business Pattern sets, one from 2010 (named "bus_patt_2010") and the other from 2016 (named "bus_patt_2016"), and the other is the Cumulative Estimates of the Components of Population Change from 2010 to 2016, which has been pared down to just the county names and key and the net migration data (named "Net_migration_2010_2016"). All were obtained from [American Fact Finder](https://factfinder.census.gov/faces/nav/jsf/pages/index.xhtml)

After downloading the datasets as .csv files, I renamed and labeled variables and dropped variables I didn't need in Stata. Additionally, in the County Business Pattern sets, I dropped all observations in which the NAICS variable didn't correspond to the count of total establishments. I uploaded the files to colab as .dta files.

###County Business Patterns 
* GEOID: a 5-digit code that identifies U.S. counties in which the first two digits refer to the state, and the last three digits indicate the county 
* countystate: the county and state, written out
* NAICS: a code that indicates different industries of the firms (The only one I kept is the total count variable, represented by 00)
* yr: year of observation
* estab: number of establishments
* employees: number of employees
* payann: establishments' annual payroll in thousands of dollars

###Net Migration Data
variables:
* GEOID: 5-digit code that identifies U.S. counties in which the first two digits refer to the state, and the last three digits indicate the county 
* countystate:the county and state, written out
* netmigration: net migration into each county from 2010 to 2016

In my final project, I will be using other datasets, but these datasets merged show the number of business establishments and their employees alongside the net migration to the counties they are in.

##Samples of datasets below
The datasets are merged on both the GEOID variable and the countystate variable for looks, but in actual use I would probably only merge on the GEOID variable due to possible differences/errors in typing/recording the full county and state.
"""

import pandas as pd

bus_patt_2016 = pd.read_stata("CBP_2016_Cleaned.dta")
print(bus_patt_2016.head())

net_mig_2016 = pd.read_stata("Net_Migration_2010_2016.dta")
print(net_mig_2016.head())

bus_patt_2010 = pd.read_stata("CBP_2010_Cleaned.dta")
print(bus_patt_2010.head())

print(list(bus_patt_2010))

print(list(net_mig_2016))

bus_patt_net_mig_2016 = bus_patt_2016.merge(net_mig_2016, on=["GEOID", "countystate"], how = "inner")
print(bus_patt_net_mig_2016.head())