# -*- coding: utf-8 -*-
"""THA3

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1yI-TGYe2WPZGU7-q-CdLF-IqZmNygGjp

#Simple research question:
##Is rurality of a county positively or negatively correlated with net migration to that county?

Since I am interested in studying the rural 'brain drain' effect, I need to be able to look at rural counties with negative net migration. In an effort to isolate counties that are rural, I used the Census Bureau's definition, which essentially uses rural as a catchall term for any areas that are not ''urban clusters" or "urbanized areas" and used the percentage of a county's population that resides in a rural area to demonstrate a county's degree of rurality.
"""

import pandas as pd
rurality = pd.read_stata("rurality.CENSUS.2010.dta")
migration = pd.read_stata("migration.ACS.2017.dta")
rurality_migration = rurality.merge(migration, on=["GEOID"], how = "inner")
print(rurality_migration.head())

#merge rurality and migration datasets, print

"""## What does this dataset do?
Ideally I would be able to run a regression to establish whether the degree to which a county is rural affects the migration into or out of that county. It would also be possible, in this case, to figure in the total population of the county or the amount of urban population, which could be used as a proxy for the county's proximity to a more urbanized area. 

The 'rural' dummy variable could also be used to isolate only those counties that are mostly rural, as these counties are my main focus in looking at changes in rural areas.

#Data Dictionary

##Description

The dataset is a combination of 2010 census data about counties' rural and urban population with 2017 ACS data of factors in population change from 2010 to 2017.

>Rurality: The Census Bureau designates urban areas with a combination of the area's population and population density. Everything outside these areas is designated as rural. The Census Bureau does not update these definitions or its estimates of rural and urban population counts between the decennial census counts, so the 2010 data is the most recent available.  

>---

>Migration: The American Community Survey collects a list of factors in population change. This includes the natural population change, births, deaths, international migration, domestic migration, and net migration, all on a county level. 

>For my purposes, I was only interested in net migration to the counties, so I isolated this variable for 2010 to 2017.


---


## Variable List
### GEOID_full
This is a longform GEOID. It isn't being used much, but it's there in case the GEOID variable isn't sufficient to merge the geographic data with another dataset
### GEOID
This is a 5-digit code that labels each county in the United States. The first two digits indicate the state (01 is Alabama, 56 is Wyoming) and the last three digits indicate the individual county within that state. This pairs with the county_state variable
### county_state
This is the county and state listing for each observation in the dataset. 
### total_population
This is the full count of each county's population as of the 2010 census
### urban_population
The urban population is the count of people in each county living in either an urban cluster or an urbanized area as of the 2010 census.
### rural_population
The rural population is the number of individuals not living in either an urban cluster or an urbanized area as of the 2010 census.
### rurality
This is the percentage of each county's population that resides in a rural area. The variable was generated by dividing the rural population by the total population of each county.
### rural
This is a dummy variable that equals 1 in counties with more than 50 percent of their population in rural areas.
### netmigration
This is the total net migration to each county from the 2010 census to the 2017 American Community Survey.
"""