# -*- coding: utf-8 -*-
"""tparlett_THA4

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aqg6xh0k7YqHB-rS1vBuyaEANf2q2zKY

# Research Question:
Is a greater number of educational institutions in a county correlated with greater degree attainment in that county?

##What does this mean?
As a proxy for access to educational institutions, the number of institutions in a given county is used to determine how much residents' level of access to institutions that grand at least 4-year degrees affects the rate of those degrees in that county.

## Operationalization:
Simple linear regression

**Independent variable:** Institution Count

**Dependent variable:** Degree attainment rate
"""

# Merge educational institutions and degree attainment datasets by county
import pandas as pd
attainment = pd.read_csv("attainment.2017.ACS5.isolatedcsv.csv")
institutions = pd.read_csv("institutions.2017.IPEDS.isolated.csv")
attainment_institutions = attainment.merge(institutions, on=["GEOID"], how = "inner")
print(attainment_institutions.head())

# pare down dataset to just attainment rate and institution count
attainment_institutions_2 = attainment_institutions[attainment_institutions.columns.difference(['population_18_up', 'degree_18_up', 'unitid', 'instnm'])]
print(attainment_institutions_2.head())

"""## Data Dictionary
### Description
The dataset is a combination of ACS 5-year estimates of educational attainment and IPEDS educational institution characteristics data.

### Variable List
**GEOID**

GEOID is a 5-digit code used to merge the previous datasets. The first two digits designate the state and the last three designate the county within that state.

**Attainment_rate**

This is a generated variable made from Census Bureau education data. 

The original dataset included population counts for population ages 18-24 and ages 25+. These were combined to generate the population ages 18+. 

The original dataset also included the number of 18-24-year-olds with a bachelors degree or higher, the number of 25+-year-olds with a bachelors degree and the number of 25+-year-olds with a graduate or professional degree. These three were combined to generate the number of people ages 18+ with at least a bachelor's degree.

attainment_rate was created by dividing the population 18+ with a degree by the full population 18+.

**instcount**

This is a variable generated from IPEDS data by counting the number of institutions that grant 4-year-plus degrees in each county.
"""

# Without institutions, drop duplicate observations
attainment_institutions_2.drop_duplicates(subset=None, keep='first', inplace=False)

import statsmodels.api as sm
import numpy as np

X = attainment_institutions_2["attainment_rate"]
y = attainment_institutions_2["instcount"]

# Note the difference in argument order
model = sm.OLS(y, X).fit()
predictions = model.predict(X) # make the predictions by the model

# Print out the statistics
model.summary()

from IPython.display import Image
Image('THA4.jpg')